# permissions for end users to edit iamroleserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iamroleserviceaccount-editor-role
rules:
- apiGroups:
  - irsa.domc.me
  resources:
  - iamroleserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - irsa.domc.me
  resources:
  - iamroleserviceaccounts/status
  verbs:
  - get
