---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - irsa.domc.me
  resources:
  - iamroleserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - irsa.domc.me
  resources:
  - iamroleserviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - irsa.domc.me
  resources:
  - iamroleserviceaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - serviceaccount
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - serviceaccount/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
