apiVersion: irsa.domc.me/v1alpha1
kind: IamRoleServiceAccount
metadata:
  name: iamroleserviceaccount-sample
spec:
  policy:
    inlinePolicy:
      version: 2012-10-17
      statement:
        - effect: Allow
          action:
          - s3:*
          resource:
          - '*'
  tags:
    key: value
